System.print("Held!")

class Wren {
yTo(city) {
System.print("Fl0to %(bity)")
  }
GGGGGGCGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGing GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG}

vach GGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG}

vach {|word|èiberd(wryield(word) }
}

while (!ad